name: "Exemplo de CD"

on:
  push:
    branches:
      - main
      - swagger

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        runner: [ip-10-0-0-181, ip-10-0-0-184]
    steps:
      - name: Pull Docker image
        run: docker pull maessio/ci-example:latest

      - name: Stop Docker container
        run: docker stop ci-example || true

      - name: Remove Docker container
        run: docker rm ci-example || true

      - name: Run Docker container
        run: docker run --name ci-example -d -p 8082:8082 --restart always maessio/ci-example:latest
