name: Exemplo

on:
  push:
    branches: [ main ]
      # - main
      # Uncomment and add more branches if needed
      # - testePipeline
      # - linkTo
    # types: [opened, reopened]

    pull_request:
      branches:
        - main
        - linkTo
      types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package -DskipTests
        working-directory: ./VITAE
      
  teste:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests with Maven
        run: mvn test
        working-directory: ./VITAE
